<a href="https://colab.research.google.com/github/meghanamattapllay/Generative-AI/blob/main/2303A52505_GEN_AI_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.(1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with the outcomes of libraries
YActual YP red
20 20.5
30 30.3
40 40.2
50 50.6
60 60.7
Tabela 1: YActual Vs. YP red


# **Without** **libraries**

In [ ]:
import numpy as np
y_actual=np.array([20,30,40,50,60])
y_pred=np.array([20.5,30.3,40.2,50.6,60.7])
print(y_actual)
print(y_pred)

[20 30 40 50 60]
[20.5 30.3 40.2 50.6 60.7]


In [ ]:
MAE= np.mean(np.abs(y_actual-y_pred))
print(MAE)

0.4600000000000016


In [ ]:
MSE= np.mean(np.square(y_actual-y_pred))
print(MSE)

0.24600000000000147


In [ ]:
RMSE= np.sqrt(np.mean(np.square(y_actual-y_pred)))
print(RMSE)

0.49598387070549127


In [ ]:
MAPE= np.mean(np.abs((y_actual-y_pred)/y_actual))*100
print(MAPE)

1.273333333333337


In [ ]:
R2= 1-(np.sum(np.square(y_actual-y_pred))/np.sum(np.square(y_actual-np.mean(y_actual))))
print(R2)

0.99877


# **With libraries**



In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [ ]:
mse=mean_squared_error(y_actual,y_pred)
print(mse)

0.24600000000000147


In [ ]:
mae=mean_absolute_error(y_actual,y_pred)
print(mae)

0.4600000000000016


In [ ]:
r2=r2_score(y_actual,y_pred)
print(r2)

0.99877


In [ ]:
mape=np.mean(np.abs((y_actual-y_pred)/y_actual))*100
print(mape)

1.273333333333337


2. (1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries
YActual YP red
0 0 1 1 2 0
0 0 1 0 2 0
0 1 1 2 2 1
0 2 1 0 2 2
0 2 1 2 2 2
Tabela 2: YActual Vs. YP red

# **Without** **libraries**

In [ ]:
y_actual=np.array([0,0,0,0,0])
y_pred=np.array([0,0,1,2,2])
print(y_actual)
print(y_pred)

[0 0 0 0 0]
[0 0 1 2 2]


In [ ]:
accuracy=np.mean(y_actual==y_pred)
print(accuracy)

0.4


In [ ]:
precision=np.mean(y_actual==y_pred)
print(precision)

0.4


In [ ]:
f1_score=2*precision*accuracy/(precision+accuracy)
print(f1_score)

0.4000000000000001


In [ ]:
recall=np.mean(y_actual==y_pred)
print(recall)

0.4


In [ ]:
confusion_matrix=np.zeros((3,3))
for i in range(len(y_actual)):
    confusion_matrix[y_actual[i],y_pred[i]]+=1
print(confusion_matrix)

[[2. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
classification_report=np.zeros((3,3))
print(classification_report)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **With libraries**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
confusion_matrix=confusion_matrix(y_actual,y_pred)
print(confusion_matrix)

[[2 1 2]
 [0 0 0]
 [0 0 0]]


In [ ]:
classification_report=classification_report(y_actual,y_pred)
print(classification_report)

              precision    recall  f1-score   support

           0       1.00      0.40      0.57         5
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0

    accuracy                           0.40         5
   macro avg       0.33      0.13      0.19         5
weighted avg       1.00      0.40      0.57         5



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
precision=precision_score(y_actual,y_pred,average='micro')
recall=recall_score(y_actual,y_pred,average='micro')
f1=f1_score(y_actual,y_pred,average='micro')
accuracy=accuracy_score(y_actual,y_pred)
print(accuracy)
print(precision)
print(recall)
print(f1)

0.4
0.4
0.4
0.4
